Add coverage and move CoffeeScript tests to TS
ensime/ensime-node pull request #31
Opened 2017-05-07 21:54 UTC by Jarlakxen

I want to contribute this changes because I think that could help to contributors to spot places to improve. Because most of the proyect is in TS, I moved CoffeeScript tests to TS. For the coverga I use this proyect as a guide https://github.com/Izhaki/Typescript-Jasmine-Istanbul-Boilerplate.
There are some minor changes in the code, most of them are just small refactors. I tried to keep the same logic and only change code styles.

2017-05-08 05:56 UTC, hedefalk requested changes
Thanks, great!

Haven't run the tests yet but I think I'll just merge first. If you could just remove that dead swank file, that'd be great!

(I'm also trying out the review functionality of github so want to request change just for the heck of it, sorry :)

2017-05-08 05:56 UTC, hedefalk commented on src/spec/swank-extras.spec.ts
> +})
This entire file could be killed off, it's just old swank protocol things which aren't used anymore…

2017-05-08 06:01 UTC, hedefalk commented
Oh, I also noticed that travis failed, could you look at that? Might be broken before though, but I would really like a working ci…

2017-05-08 10:49 UTC, Jarlakxen commented
I just checked Travis, the test are failing due to the node version. It look like that ts-node only works with node >= 6 and the test are running with 4 and 5.

2017-05-08 10:54 UTC, hedefalk commented
Ah, ok. I'm all for latest and greatest, but do we really need ts-node? (Had googled what it was)

Isn't it better to just run tests from compiled js?

2017-05-08 11:16 UTC, Jarlakxen commented on src/spec/swank-extras.spec.ts
> +})
Sure! No problem. Only the spec? or also the swank-extras.ts?

2017-05-08 11:22 UTC, hedefalk commented
I think it might still be needed to parse the .ensime file but that test
definitely is "dead code"

On Mon, May 8, 2017 at 1:16 PM Facundo Viale <notifications@github.com>
wrote:

> *@Jarlakxen* commented on this pull request.
> ------------------------------
>
> In src/spec/swank-extras.spec.ts
> <https://github.com/ensime/ensime-node/pull/31#discussion_r115220909>:
>
> > +    const result = arrToJObject(arr)
> +
> +    expect(result[0][0][0]).toBe('x')
> +    expect(result[0][1][1]).toBe('Int')
> +  })
> +
> +  it('should parse scala notes', () => {
> +    const input = `
> +        (:scala-notes (:is-full nil :notes ((:file "/Users/viktor/dev/projects/kostbevakningen/src/main/scala/se/kostbevakningen/model/record/Ingredient.scala" :msg "missing
> +        arguments for method test in object Ingredient; follow this method with \`_' if you want to treat it as a partially applied function" :severity error :beg 4138 :end 4142 :line 105 :col 3))))
> +    `
> +
> +    const result = sexpToJObject(readFromString(input))
> +    expect(result[':scala-notes'][':notes'].length).toBe(1)
> +  })
> +})
>
> Sure! No problem. Only the spec? or also the swank-extras.ts?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/ensime/ensime-node/pull/31#discussion_r115220909>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAHHKO_GMHZUoxvt08llvTAjF_lHgm_nks5r3vmBgaJpZM4NTUKW>
> .
>

2017-05-08 11:35 UTC, Jarlakxen commented
I'm using ts-node in a very similar way to https://babeljs.io/docs/usage/babel-register/. I choosed ts-node because I found it much easier to integrate with Istanbul. I think, if we choose to compile the files, we need to use https://github.com/SitePen/remap-istanbul to remap Istanbul code coverage information to its original source. I didn't found a good example of remap-istanbul + jasmine + TS.
But I'm open to other solutions =D

2017-05-21 14:40 UTC, Jarlakxen commented
Any thoughts? =)

2017-05-21 18:09 UTC, hedefalk commented
@Jarlakxen Sorry I haven't answered, been super busy…

I'm open to suggestsions, just want that green tick basically :)

2017-05-21 18:55 UTC, hedefalk approved these changes

2017-05-21 18:55 UTC, merged

2017-05-21 18:56 UTC, hedefalk commented
Thx!

2017-05-21 18:56 UTC, Jarlakxen commented
No problem! 
I the meantime, I was working on other PRs =D

2017-05-21 18:57 UTC, hedefalk commented
Great! They are much welcome!